title: Mental Health for Every Adolescent
email: contact@projectmhea.org
description: Website of Mental Health for Every Adolescent
baseurl: ""
url: "https://projectmhea.org"

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "defualt"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
