title: Mental Health for Every Adolescent
email: contact@projectmhea.org
description: Website of Mental Health for Every Adolescent
baseurl: ""
url: "https://projectmhea.org"

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
